### ISSUE TITLE
Plugin doesn't work in release version on android devices

### ISSUE THREAD

**Issue by garrenc** [cheebeez/radio_player#3]
Radio player works perfectly in debug mode, but when i try to launch it in release version, app stops responding. I allowed these permissions in release manifest file:

`<uses-permission android:name="android.permission.INTERNET"/>`
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>`
`<uses-permission android:name="android.permission.WAKE_LOCK"/>`

Then I tried to change shrinkResources and minifyEnabled in build.gradle file:

```
buildTypes {
     release {
        signingConfig signingConfigs.release
       shrinkResources false
       minifyEnabled false
    }
 }
```
 But it still didn't work.
 I don't if it is plugin's error or me doing something wrong.

**Comment by cheebeez** [comment]
Hello. 
I double-checked it and in my case the app works without any problems.
Permissions is already allowed in radio_player/android/src/main/AndroidManifest.xml
What version of Android are you using?

**Comment by garrenc** [comment]
I have Android 10

**Comment by garrenc** [comment]
It actually works on the first launch after installation, but it stops working when I close app and launch it second time

**Comment by cheebeez** [comment]
I don't see this problem on Android 10 (pixel 4) and Android 8.1 (honor 7a)

**Comment by danielns1982** [comment]
Same problem here. Android version 9. Works on the first launch, then freeze with message app isn't responding.

**Comment by cheebeez** [comment]
> Same problem here. Android version 9. Works on the first launch, then freeze with message app isn't responding.

Can you give me a apk? even better with source code.

**Comment by danielns1982** [comment]
Stack trace when error occurs:

E/flutter (29051): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, lateinit property service has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property service has not been initialized
E/flutter (29051):      at com.cheebeez.radio_player.RadioPlayerPlugin.onMethodCall(RadioPlayerPlugin.kt:97)
E/flutter (29051):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (29051):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (29051):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (29051):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (29051):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (29051):      at android.os.Looper.loop(Looper.java:183)
E/flutter (29051):      at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (29051):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (29051):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (29051):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (29051): )
E/flutter (29051): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (29051): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (29051): <asynchronous suspension>
E/flutter (29051): #2      RadioPlayer.setMediaItem (package:radio_player/radio_player.dart:25:5)
E/flutter (29051): <asynchronous suspension>
E/flutter (29051):

**Comment by danielns1982** [comment]
> > Same problem here. Android version 9. Works on the first launch, then freeze with message app isn't responding.
> 
> Can you give me a apk? even better with source code.

I got source code from https://pub.dev/packages/radio_player/example without change a single line.

Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (3 weeks ago) • 2021-06-11 08:56:01 -0700
Tools • Dart 2.13.3

**Comment by cheebeez** [comment]
I can't reproduce this bug. 
Please download repository and try to build "radio_player/example/lib/main.dart" for emulator.

**Comment by danielns1982** [comment]
> I can't reproduce this bug.
> Please download repository and try to build "radio_player/example/lib/main.dart" for emulator.

Same error:

![Screenshot_1625000649](https://user-images.githubusercontent.com/16790035/123867334-38215980-d8fc-11eb-816e-0efe2a7347db.png)

**Comment by cheebeez** [comment]
I will fix it. Thanks.

**Comment by danielns1982** [comment]
> I will fix it. Thanks.

Thank you.

**Comment by cheebeez** [comment]
Hopefully the problem is fixed in 0.2.3.

**Comment by danielns1982** [comment]
ANR solved, but radio play still not working as before. In other words app don't crash anymore but play button do nothing.

**Comment by danielns1982** [comment]
Just to be clear, this only happens from the second time the app is opened onwards.

**Comment by danielns1982** [comment]
Worked perfectly. Thank you so much!
